# Properties for Android build specific to this game.
cmakelists=CMakeLists.txt
manifest=AndroidManifest.xml
resDir=res/android
assetsDir=assets_built
buildDir=build.android
versionName=1.0.0
versionCode=1000000
appId=com.bearwaves.mytitle
# keystore=keystore.properties
# additionalModule=src/java
